"""game board dimensions

Revision ID: 0c7b8f667bae
Revises: 13cbf674d578
Create Date: 2025-01-02 18:53:57.743159

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "0c7b8f667bae"
down_revision = "13cbf674d578"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("game", schema=None) as batch_op:
        batch_op.add_column(sa.Column("width", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("heigth", sa.Integer(), nullable=True))
        batch_op.alter_column(
            "uuid",
            existing_type=sa.INTEGER(),
            type_=sa.String(length=36),
            existing_nullable=False,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("game", schema=None) as batch_op:
        batch_op.alter_column(
            "uuid",
            existing_type=sa.String(length=36),
            type_=sa.INTEGER(),
            existing_nullable=False,
        )
        batch_op.drop_column("heigth")
        batch_op.drop_column("width")

    # ### end Alembic commands ###
