"""game board update and create times

Revision ID: 453e2eb0a177
Revises: 0c7b8f667bae
Create Date: 2025-01-02 19:45:18.685419

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "453e2eb0a177"
down_revision = "0c7b8f667bae"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("game", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("created_at", sa.DateTime(timezone=True), nullable=True)
        )
        batch_op.add_column(
            sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True)
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("game", schema=None) as batch_op:
        batch_op.drop_column("updated_at")
        batch_op.drop_column("created_at")

    # ### end Alembic commands ###
