"""user with hashed passwords

Revision ID: cc6b362d2f09
Revises: 7a20dc237165
Create Date: 2025-02-11 20:28:03.797851

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc6b362d2f09'
down_revision = '7a20dc237165'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.Text(), nullable=False))
        batch_op.drop_column('password')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.TEXT(), nullable=False))
        batch_op.drop_column('password_hash')

    # ### end Alembic commands ###
